export const SET_LATITUDE = 'SET_LATITUDE'

export const SET_LONGITUDE = 'SET_LONGITUDE'

export const SET_CART_LIST = 'SET_CART_LIST'

export const ADD_CART = 'ADD_CART'

export const REDUCE_CART = 'REDUCE_CART'

export const INIT_BUYCART = 'INIT_BUYCART'

export const CLEAR_CART = 'CLEAR_CART'

export const RECORD_SHOPDETAIL = 'RECORD_SHOPDETAIL'

export const RECORD_USERINFO = 'RECORD_USERINFO'

export const GET_USERINFO = 'GET_USERINFO'
