export const SET_LATITUDE = 'SET_LATITUDE'

export const SET_LONGITUDE = 'SET_LONGITUDE'

export const SET_GEOHASH = 'SET_GEOHASH'

export const SET_CART_LIST = 'SET_CART_LIST'

export const ADD_CART = 'ADD_CART'

export const REDUCE_CART = 'REDUCE_CART'

export const INIT_BUYCART = 'INIT_BUYCART'

export const CLEAR_CART = 'CLEAR_CART'

export const RECORD_SHOPDETAIL = 'RECORD_SHOPDETAIL'

export const RECORD_USERINFO = 'RECORD_USERINFO'

export const GET_USERINFO = 'GET_USERINFO'

export const GET_CONFIRM_REMARK = 'GET_CONFIRM_REMARK'

export const CONFIRM_INVOICE = 'CONFIRM_INVOICE'

export const CHOOSE_SEARCH_ADDRESS = 'CHOOSE_SEARCH_ADDRESS'

export const CHOOSE_ADDRESS = 'CHOOSE_ADDRESS'
